# Generated by Django 5.2.7 on 2025-11-06 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcontent',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcontent',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcontent',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignAnalyticsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_ctr', models.FloatField(default=0)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_conversion_rate', models.FloatField(default=0)),
                ('roas', models.FloatField(default=0)),
                ('performance_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summary', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.FloatField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='core.campaign')),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
