# Generated by Django 5.2 on 2025-11-08 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abtest_adplatformconnection_reportschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('tiktok_ads', 'TikTok Ads'), ('linkedin_ads', 'LinkedIn Ads')], max_length=20)),
                ('api_name', models.CharField(max_length=100)),
                ('encrypted_key', models.TextField()),
                ('encrypted_secret', models.TextField(blank=True)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('developer_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'api_type', 'api_name')},
            },
        ),
    ]
