# Generated by Django 4.2.26 on 2025-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
