# Generated by Django 4.2.26 on 2025-11-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imageasset_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageasset',
            old_name='image',
            new_name='image_url',
        ),
    ]
