# Generated by Django 4.2.26 on 2025-11-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_imageasset_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageasset',
            old_name='image_url',
            new_name='image',
        ),
    ]
